MyBookStore/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using MyBookStore.BusinessLogic;
using MyBookStore.Entities;
using MyBookStore.Entities.Interfaces;


namespace MyBookStore.Controllers
{
    /// <summary>
    /// Class to List, and Search for Books
    /// </summary>
    public class BookController : Controller
    {
        // GET: Book
        public ActionResult Index()
        {
            try
            {
                List<IBook> books = BSUtility.BookStoreService.GetBooks();
                return View(books);
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = "An Error Occurred, Error" + e.Message;
                return View(new List<IBook>());
            }
        }

        [HttpGet, ActionName("GetBooks")]
        public ActionResult GetBooks(string title,string author)
        {
            try
            {
                List<IBook> books = BSUtility.BookStoreService.GetBooks(author, title);
                return PartialView("~/Views/Shared/_ListOfBooks.cshtml", books);
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = "An Error Occurred, Error" + e.Message;
                return Content("An Error Occurred, Error" + e.Message);
            }
        }
              
     }
}

MyBookStore/Controllers/CartController.cs
using MyBookStore.BusinessLogic;
using MyBookStore.Entities.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyBookStore.Controllers
{
    /// <summary>
    /// Class to Addd items to cart, list them and place the order
    /// </summary>
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            try
            {
                ICart cart = BSUtility.BookStoreService.GetCart();
                return View(cart);
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = "An Error Occurred, Error" + e.Message;
                ICart cart = null;
                return View(cart);
            }
}

        [HttpGet, ActionName("AddToCart")]
        public ActionResult AddToCart(string ISBN)
        {
            try
            {
                BSUtility.BookStoreService.AddToCart(ISBN, 1);
                return Content("true");
            }
            catch (Exception e)
            {
                return Content("An Error Occurred, Error" + e.Message);
            }
        }

        [HttpGet, ActionName("PlaceOrder")]
        public ActionResult PlaceOrder()
        {
            try
            {
                ICart cart = BSUtility.BookStoreService.GetCart();
                BSUtility.BookStoreService.PlaceOrder();
                return View(cart);
            }
            catch (Exception e)
            {
                ViewBag.ErrorMessage = "An Error Occurred, Error" + e.Message;
                ICart cart = null;
                return View(cart);
            }
        }
    }
}

MyBookStore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyBookStore.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MyBookStore/Views/Book/Index.cshtml
@model List<IBook>
@using MyBookStore.Entities.Interfaces;

@{
    /**/

    ViewBag.Title = "Books";
    var errDisplay = "none";
}

<h2>Books</h2>


    <div id="searchBooks">
        <div>
            <label>Title</label><input type="text" class="form-control" id="txtSearchTitle" placeholder="Search" onkeyup="getBooks()" />
        </div>
        <div>
            <label>Author</label><input type="text" class="form-control" id="txtSearchAuthor" placeholder="Search" onkeyup="getBooks()" />
        </div>
    </div>

    
    <div id="divBooks">
        @if (ViewBag.ErrorMessage != null && ViewBag.ErrorMessage != "")
        {
            errDisplay = "block";
        }
        else
        {

            @Html.Partial("~/Views/Shared/_ListOfBooks.cshtml", Model)

        }
    </div>
            <div id="divError" style="display: @errDisplay;">
                <label id="lblError" class="alert-danger">@ViewBag.ErrorMessage</label>
            </div>
            <div id="divInfo" style="display: @errDisplay;">
                <label id="lblInfo" class="alert-success"></label>
            </div>

<div id="divProcessing" class="processingButton" style="display: none;">
    <img width="31" height="31" alt="" class="LoadingImage" src="~/Images/ajax-loader-round.gif" />
</div>

<script type="text/javascript">

    var timer;

        function getBooks() {
            clearTimeout(timer);
            timer = setTimeout(function () {
                $.ajax({
                    url: '@Url.Action("GetBooks", "Book")',
                    dataType: "html",
                    data: { title: $('#txtSearchTitle').val(), author: $('#txtSearchAuthor').val() },
                    type: "Get",
                    success: function (data) {
                        $("#divProcessing").hide();
                        if (data.indexOf("Error") != -1) {
                            $("#divError").show();
                            $("#lblError").text(data);
                        }
                        else
                            $('#divBooks').html(data);
                    },
                    beforeSend: function () {
                        $("#divProcessing").show();
                        $("#divError").hide();
                        $("#divInfo").hide();
                    }
                });
            });
        }

        function addToCart(button, bookNumber) {
            $.ajax({
                    url: '@Url.Action("AddToCart", "Cart")',
                    dataType: "html",
                data: { ISBN: bookNumber},
                    type: "Get",
                    success: function (data) {
                        $("#divProcessing").hide();
                        if (data != "true")
                        {
                            $("#divError").show();
                            $("#lblError").text(data);
                        }
                        else
                        {
                            $("#divInfo").show();
                            $("#lblInfo").text('Book Added To Cart')
                        }
                    },
                    beforeSend: function () {
                        $("#divProcessing").show();
                        $("#divError").hide();
                        $("#divInfo").hide();
                    }
                })
        }

</script>

MyBookStore/Views/Cart/Index.cshtml
@model ICart
@using MyBookStore.Entities.Interfaces;

@{
    ViewBag.Title = "Cart";
    var errDisplay = "none";
}



@if (ViewBag.ErrorMessage != null && ViewBag.ErrorMessage != "")
{
    errDisplay = "block";
}
else
{
    <h2>Cart - Total Value:@Model.TotalValue</h2>
    <div id="divBooks">
        @Html.Partial("~/Views/Cart/_Cart.cshtml", Model.Items)
    </div>

    if (Model.Items.Count > 0)
    {
        <div>
            @Html.ActionLink("Place Order", "PlaceOrder", "Cart")
        </div>
    }
}
<div id="divError" style="display: @errDisplay;">
    <label id="lblError" class="alert-danger">@ViewBag.ErrorMessage</label>
</div>

MyBookStore/Views/Cart/PlaceOrder.cshtml
@model ICart
@using MyBookStore.Entities.Interfaces;
@{
    ViewBag.Title = "Order";
    var errDisplay = "none";
}


@if (ViewBag.ErrorMessage != null && ViewBag.ErrorMessage != "")
{
    errDisplay = "block";
}
else
{
    <h2>Order Total: @Model.OrderValue</h2>

    <div id="divAvailableBooks">
        @Html.Partial("~/Views/Cart/_Cart.cshtml", Model.AvailableBooks)
    </div>

    if (Model.UnAvailableBooks.Count > 0)
    {
        <h2>Unavailable Books</h2>
        <div id="divUnAvailableBooks">
            @Html.Partial("~/Views/Cart/_Cart.cshtml", Model.UnAvailableBooks)
        </div>
    }
}
<div id="divError" style="display: @errDisplay;">
    <label id="lblError" class="alert-danger">@ViewBag.ErrorMessage</label>
</div>

MyBookStore/Views/Cart/_Cart.cshtml
@model List<IBook>
@using MyBookStore.Entities.Interfaces;



<table class="table-responsive table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th style="text-align:right">Price</th>
            <th style="text-align:right">Quantity</th>
            <th style="text-align:right">Vaue</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count > 0)
        {
            foreach (var book in Model)
            {
        <tr>
            <td>@book.Title</td>
            <td>@book.Author</td>
            <td align="right">@book.Price</td>
            <td align="right">@book.CartQuantity</td>
            @{
                decimal price = book.CartQuantity * book.Price;
            }
            <td align="right">@price</td>
        </tr>
            }
        }
        else
        {
            <tr>
                <td>
                    No Books Found
                </td>
            </tr>
        }
    </tbody>
</table>

MyBookStore/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MyBookStore/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>


<address>
   <abbr title="Phone">Phone:</abbr>
    07614253040
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:prasannadsouza@gmail.com">prasannadsouza@gmail.com</a><br />
   
</address>

MyBookStore/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MyBookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Book Store</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("My Book Store", "Index", "Book", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Book")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Books", "Index", "Book")</li>
                    <li>@Html.ActionLink("Cart", "Index", "Cart")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Book Store</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MyBookStore/Views/Shared/_ListOfBooks.cshtml
@model List<MyBookStore.Entities.Interfaces.IBook>

<table class="table-responsive table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Author</th>
            <th style="text-align:right">Price</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count > 0)
        {
            foreach (var book in Model)
            {
        <tr>
            <td>@book.Title</td>
            <td>@book.Author</td>
            <td align="right">@book.Price</td>
            <td align="center">
               
                    <a href="javascript:addToCart(this,'@book.ISBN');">Add To Cart</a>
                
            </td>
        </tr>
            }
        }
        else
        {
            <tr>
                <td>
                    No Books Found
                </td>
            </tr>
        }
    </tbody>
</table>



    